import type { Metadata } from "next";
import Image from "next/image"; // <-- import next/image
import "./globals.css";

export const metadata: Metadata = {
  title: "Sohcahtoa Employee Investment Details Form",
  description: "Generated by Sohcahtoa Employee Investment Details Form",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favi.jpg" type="image/jpg" />
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
